### ISSUE TITLE
Add example of how a batch request is formatted

### ISSUE THREAD

**Issue by Munhuggas** [braze-inc/braze-docs#7397]
### Feature description
Please add an example for how batch requests are supposed to be formatted.

**Comment by internetisaiah** [comment]
Hey @Munhuggas ,

Thanks for reaching out! When you say "batch requests" are you referring to batch API requests? Also, is there a particular page on Braze Docs you had in mind? I can create a ticket for this request once I have that information 👍🏽

**Comment by Munhuggas** [comment]
Hi!

Thanks for getting back so quickly. This is the page I found in the documentation. Would love to just have a tiny example of how the request is supposed to look like.

https://www.braze.com/docs/api/api_limits/

**Comment by internetisaiah** [comment]
Awesome! I will create a ticket for our team. Thanks for the info!

**Comment by internetisaiah** [comment]
Hey @Munhuggas , this has been fixed in the `develop` branch and should be live by EOD next Tuesday after our deploy. In the meantime, here's the [page in our test environment](https://braze-docs-b7seayh50-braze.vercel.app/api/api_limits/#example-batch-request) if you need to reference it for work you're doing 👍🏽

**Comment by Munhuggas** [comment]
@internetisaiah Thanks for the swift update! Does this pattern generalize to all API calls? The one I am making is a call to https://www.braze.com/docs/api/endpoints/messaging/send_messages/post_send_triggered_campaigns/
